version: "3.8"

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '${ZOOKEEPER_PORT}:${ZOOKEEPER_PORT}'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '${KAFKA_PORT}:${KAFKA_PORT}'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:${KAFKA_PLAINTEXT_PORT}
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:${KAFKA_PLAINTEXT_PORT}
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:${ZOOKEEPER_PORT}
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper